### ISSUE TITLE
Support for having 404.html files in contexts for nested apps?

### ISSUE THREAD

**Issue by gashcrumb** [jimmidyson/kuisp#3]
Just added /java/ to fabric8-console to split out all the java/jmx stuff into a separate app.  Wondering if it'd be possible to support looking for 404.html files if a path on the disk can't be found, i.e. if I'm at `http://localhost/java/jmx/attributes` and click refresh I get `index.html` from the root context, whereas ideally I'd like to see if we can get the `/java/404.html` file served instead, otherwise you wind up back in the regular fabric8 console and not in the java console.

**Comment by jimmidyson** [comment]
@gashcrumb OK so look in current dir & then traverse up the tree until find a 404.html or something like that?

**Comment by gashcrumb** [comment]
yeah, that'd be awesome!  If only I could have written that up so concise :-)

**Comment by jimmidyson** [comment]
Out of interest, have you tried just an `index.html` in the `/java` dir?

**Comment by jimmidyson** [comment]
Yeah that should work - just add index.html to any dir you want to be loadable directly.

**Comment by gashcrumb** [comment]
huh, I have one, but refreshed at /java/jmx/attributes/ and wound up back at the fabric8-console home page...  Well, will give it another test in a few.

**Comment by jimmidyson** [comment]
Did you get a redirect or the root page served at that location? kuisp doesn't do redirects iirc.

**Comment by gashcrumb** [comment]
I think the root page...  Got sidetracked, will investigate in a few.

**Comment by jimmidyson** [comment]
Should be fixed in 0.13.1
